services:
  - type: web
    name: wavedrive-service
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --workers=1 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
